### ISSUE TITLE
延迟调用再this.forceUpdate()的原因是什么，上边已经调用过this.forceUpdate()了

### ISSUE THREAD

**Issue by hnny09** [axerjs/react-native-waterfall-flow#18]

**Comment by axeryu** [comment]
请问有解决掉你之前的问题吗，或是有出现新的问题？
具体实现原理我后面会写博客说明

**Comment by axeryu** [comment]
> 嗯，感觉问题挺多的，会有重复渲染的问题，item一直在跳动的问题

能把你调用瀑布流的代码发我看看吗，我这边运行没出现过你说的问题

**Comment by axeryu** [comment]
您更新到v1.1.1看看，如果有问题欢迎随时联系

**Comment by axeryu** [comment]
ios确实会有闪动的情况，昨天连夜修复了一版，麻烦更新到v1.1.1，如果没问题了也麻烦告知一声

**Comment by hnny09** [comment]
具体修改点是什么，我看下

**Comment by axeryu** [comment]
> 具体修改点是什么，我看下
onitemheightchange里面的判断逻辑有改动

**Comment by hnny09** [comment]
你没有入库吧？

**Comment by axeryu** [comment]
> 具体修改点是什么，我看下

github还没来得及提交，npm安装v1.1.1可以看源码

**Comment by hnny09** [comment]
提交一下吧，我改了部分代码了

**Comment by axeryu** [comment]
不好意思，这两天出差没携带开发电脑，您先安装新版本试试

**Comment by axeryu** [comment]
更细节的问题咱们可以邮箱沟通
18672320768@163.com
