### ISSUE TITLE
高低组件切换会出现定位不对的问题

### ISSUE THREAD

**Issue by ikmil** [axerjs/react-native-waterfall-flow#21]
if (this._itemHeights[index] !== height) {
                  const preAllLoaded = !JSON.parse(JSON.stringify(this._itemHeights)).some(o => o === null)
                  this._itemHeights[index] = height
                  const allLoaded = !JSON.parse(JSON.stringify(this._itemHeights)).some(o => o === null)
                  if (allLoaded && !preAllLoaded) {
                    this._computePositions()
                  }
                }

这段代码的具体含义是什么意思 主要是preAllLoaded和allLoaded 这2个变量没看太懂，在我的实际项目中，数据切换会展示不同高度的组件，但是会出现问题，比如切换前有个组件占据了500的高度，切换成300高度的组件的时候，那个位置依然占据着200的高度，导致下一个组件的定位就是按500计算的，我重复赋值的话就对了，我发现是_computePositions这个方法调用了的情况就是对的，出错的时候都是没吊用这个方法，但是这个调用的前置条件没太明白含义

**Comment by axeryu** [comment]
如果是会变化高度的组件，可以在合适的时机手动调用_computePositions方法

**Comment by axeryu** [comment]
allLoaded的含义是所有item全部加在完成

**Comment by ikmil** [comment]
> 

那allLoaded && !preAllLoaded 这个是什么意思呢，按理说如果是10条数据，那_itemHeights就应该存了10条数据，第二次再次改变数据，但也是10条，那这里面原本已经存了上一次的数据，不会有null的数据存在，这里这个判断是什么意思呢？也就是说_itemHeights一直都存在有10 条非null数据，如何去判断的全部加载完成的？只有第一次加载这个用null判断的逻辑才合理吧，我现在是在里面加了个定时器，调用forceUpdate强制渲染，页面到能显示正常，但是明显不合理，想请教下，如何判断加载完成

**Comment by axeryu** [comment]
其实瀑布流默认不支持会变化高度的组件的，我这周末会支持这个功能，到时候你可以再看看新版源码

**Comment by ikmil** [comment]
> 其实瀑布流默认不支持会变化高度的组件的，我这周末会支持这个功能，到时候你可以再看看新版源码

是否有思路可提供参考下，我卡在了不知道如何判断它已经加载完成了-。-！

**Comment by axeryu** [comment]
已经发布新版本1.1.2，去掉了preAllLoaded判断，只要所有item都初始渲染完成后，一旦有item高度发生变化，立即更新瀑布流布局

![image](https://user-images.githubusercontent.com/22517261/198826433-81f822cd-3749-492c-952f-9a2b426de9ae.png)

**Comment by ikmil** [comment]
> 已经发布新版本1.1.2，去掉了preAllLoaded判断，只要所有item都初始渲染完成后，一旦有item高度发生变化，立即更新瀑布流布局
> 
> ![image](https://user-images.githubusercontent.com/22517261/198826433-81f822cd-3749-492c-952f-9a2b426de9ae.png)

我的理解const allLoaded = !JSON.parse(JSON.stringify(this._itemHeights)).some(o => o === null) 这句代码只能第一页以及数据增加时才能判断已经加载完了，但是原本就有数据的情况，我不清空数据，重新赋值，这种情况下不能判断到吧，就是我说的原本有10条数据，我重新给了新的10条数据，这时_computePositions应该会被调用10次

**Comment by axeryu** [comment]
> > 已经发布新版本1.1.2，去掉了preAllLoaded判断，只要所有item都初始渲染完成后，一旦有item高度发生变化，立即更新瀑布流布局
> > ![image](https://user-images.githubusercontent.com/22517261/198826433-81f822cd-3749-492c-952f-9a2b426de9ae.png)
> 
> 我的理解const allLoaded = !JSON.parse(JSON.stringify(this._itemHeights)).some(o => o === null) 这句代码只能第一页以及数据增加时才能判断已经加载完了，但是原本就有数据的情况，我不清空数据，重新赋值，这种情况下不能判断到吧，就是我说的原本有10条数据，我重新给了新的10条数据，这时_computePositions应该会被调用10次

allLoaded里面的this._itemHeights的长度会实时与你的数据源长度保持一致的，你可以再多理解理解

**Comment by axeryu** [comment]
> > > 已经发布新版本1.1.2，去掉了preAllLoaded判断，只要所有item都初始渲染完成后，一旦有item高度发生变化，立即更新瀑布流布局
> > > ![image](https://user-images.githubusercontent.com/22517261/198826433-81f822cd-3749-492c-952f-9a2b426de9ae.png)
> > 
> > 
> > 我的理解const allLoaded = !JSON.parse(JSON.stringify(this._itemHeights)).some(o => o === null) 这句代码只能第一页以及数据增加时才能判断已经加载完了，但是原本就有数据的情况，我不清空数据，重新赋值，这种情况下不能判断到吧，就是我说的原本有10条数据，我重新给了新的10条数据，这时_computePositions应该会被调用10次
> 
> allLoaded里面的this._itemHeights的长度会实时与你的数据源长度保持一致的，你可以再多理解理解



> > 已经发布新版本1.1.2，去掉了preAllLoaded判断，只要所有item都初始渲染完成后，一旦有item高度发生变化，立即更新瀑布流布局
> > ![image](https://user-images.githubusercontent.com/22517261/198826433-81f822cd-3749-492c-952f-9a2b426de9ae.png)
> 
> 我的理解const allLoaded = !JSON.parse(JSON.stringify(this._itemHeights)).some(o => o === null) 这句代码只能第一页以及数据增加时才能判断已经加载完了，但是原本就有数据的情况，我不清空数据，重新赋值，这种情况下不能判断到吧，就是我说的原本有10条数据，我重新给了新的10条数据，这时_computePositions应该会被调用10次

这种情况相当于完全换了一次数据源吧，如果这种情况渲染有抖动，建议你清空数据源再赋值

**Comment by ikmil** [comment]
> 

对，相当于数据源变了，数量没变，所以你这个判断方式就判断不了，如果清空之后再赋值的话，实际你改之前的代码也是没问题（现在反而会产生大量的_computePositions调用），只是清空数据这个操作不符合我的预期，页面高度会产生变化。

**Comment by axeryu** [comment]
> > 
> 
> 对，相当于数据源变了，数量没变，所以你这个判断方式就判断不了，如果清空之后再赋值的话，实际你改之前的代码也是没问题（现在反而会产生大量的_computePositions调用），只是清空数据这个操作不符合我的预期，页面高度会产生变化。

新版代码是否会造成页面卡顿或抖动

**Comment by ikmil** [comment]
> 

会

**Comment by axeryu** [comment]
> > 
> 
> 会

急吗，我明晚才有时间看

**Comment by ikmil** [comment]
> > > 
> > 
> > 
> > 会
> 
> 急吗，我明晚才有时间看

还挺急的，目前卡这儿了，现在的问题点应该还是一样，就是什么时候去调用渲染页面这个方法（如何判断组件加载完闭了）

**Comment by ikmil** [comment]
> > > > 
> > > 
> > > 
> > > 会
> > 
> > 
> > 急吗，我明晚才有时间看
> 
> 还挺急的，目前卡这儿了，现在的问题点应该还是一样，就是什么时候去调用渲染页面这个方法（如何判断组件加载完闭了）

数据清空一次我页面高度会变化，这样我原本页面中的分类是吸顶的，会突然被拉下来，体验是不符合预期的，我先找有没有其它交互方案优化这个体验，这个问题您抽空研究下吧，另外吸顶这个是很常见的，但是在现有条件下实现还是挺麻烦的，后期您可以考虑优化一下，另外在组件外调用组件内的方法好像调用不到，会调用到flatlist自己的方法，而不是你重写的方法，比如scrollToIndex

**Comment by axeryu** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 会
> > > 
> > > 
> > > 急吗，我明晚才有时间看
> > 
> > 
> > 还挺急的，目前卡这儿了，现在的问题点应该还是一样，就是什么时候去调用渲染页面这个方法（如何判断组件加载完闭了）
> 
> 数据清空一次我页面高度会变化，这样我原本页面中的分类是吸顶的，会突然被拉下来，体验是不符合预期的，我先找有没有其它交互方案优化这个体验，这个问题您抽空研究下吧，另外吸顶这个是很常见的，但是在现有条件下实现还是挺麻烦的，后期您可以考虑优化一下，另外在组件外调用组件内的方法好像调用不到，会调用到flatlist自己的方法，而不是你重写的方法，比如scrollToIndex

我这边只提供瀑布流基础能力，不会做过多扩展，像吸顶这种你可以做二次封装，scrollToIndex肯定会走进我的方法的，毕竟没有直接继承Flatlist。清空数据页面高度会变化这个问题你可以设置一个ListEmptyComponent, 给个占位高度就好了

**Comment by ikmil** [comment]
> 

调用方法那个是我的问题，我取错实例了，数据变化但数据量没变的情况，您研究下吧

**Comment by ikmil** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 会
> > > > 
> > > > 
> > > > 急吗，我明晚才有时间看
> > > 
> > > 
> > > 还挺急的，目前卡这儿了，现在的问题点应该还是一样，就是什么时候去调用渲染页面这个方法（如何判断组件加载完闭了）
> > 
> > 
> > 数据清空一次我页面高度会变化，这样我原本页面中的分类是吸顶的，会突然被拉下来，体验是不符合预期的，我先找有没有其它交互方案优化这个体验，这个问题您抽空研究下吧，另外吸顶这个是很常见的，但是在现有条件下实现还是挺麻烦的，后期您可以考虑优化一下，另外在组件外调用组件内的方法好像调用不到，会调用到flatlist自己的方法，而不是你重写的方法，比如scrollToIndex
> 
> 我这边只提供瀑布流基础能力，不会做过多扩展，像吸顶这种你可以做二次封装，scrollToIndex肯定会走进我的方法的，毕竟没有直接继承Flatlist。清空数据页面高度会变化这个问题你可以设置一个ListEmptyComponent, 给个占位高度就好了

ListEmptyComponent 也不适用，因为listheader是可以滑动上去的且是一个整体，需要吸顶的分类在页面中间位置，滑到它的位置才吸顶，所以只能放到data里去，通过renderItem去渲染才能符合预期，data里相当于一直有值，存的是需要吸顶的分类组件，所以ListEmptyComponent是无法触发的

**Comment by axeryu** [comment]
试试v1.1.3

**Comment by axeryu** [comment]
> > > > > 会
> > > > 
> > > > 
> > > > 急吗，我明晚才有时间看
> > > 
> > > 
> > > 还挺急的，目前卡这儿了，现在的问题点应该还是一样，就是什么时候去调用渲染页面这个方法（如何判断组件加载完闭了）
> > 
> > 
> > 数据清空一次我页面高度会变化，这样我原本页面中的分类是吸顶的，会突然被拉下来，体验是不符合预期的，我先找有没有其它交互方案优化这个体验，这个问题您抽空研究下吧，另外吸顶这个是很常见的，但是在现有条件下实现还是挺麻烦的，后期您可以考虑优化一下，另外在组件外调用组件内的方法好像调用不到，会调用到flatlist自己的方法，而不是你重写的方法，比如scrollToIndex
> 
> 我这边只提供瀑布流基础能力，不会做过多扩展，像吸顶这种你可以做二次封装，scrollToIndex肯定会走进我的方法的，毕竟没有直接继承Flatlist。清空数据页面高度会变化这个问题你可以设置一个ListEmptyComponent, 给个占位高度就好了

v1.1.3OK了吗
