### ISSUE TITLE
item闪烁是啥问题

### ISSUE THREAD

**Issue by Liqiankun** [axerjs/react-native-waterfall-flow#24]
https://user-images.githubusercontent.com/11532418/201862974-f5ed0f24-f20a-4ebd-a1f7-e9280759546c.mov

**Comment by axeryu** [comment]
> 2022-11-15.16.02.02.mov

用的什么版本，真机试了吗

**Comment by axeryu** [comment]
> 2022-11-15.16.02.02.mov

用的什么版本，真机试了吗

**Comment by axeryu** [comment]
> 2022-11-15.16.02.02.mov

使用最新1.1.4版本，应该是没问题吧
