### ISSUE TITLE
item 超出rowitem高度时，无法回调点击事件问题

### ISSUE THREAD

**Issue by hnny09** [axerjs/react-native-waterfall-flow#29]
item 超出rowitem高度时，无法回调点击事件问题，请问有什么解决办法吗？

**Comment by Mrxyx** [comment]
遇到同样的问题，使用react-native-gesture-handler的点击事件解决了

**Comment by hnny09** [comment]
> 遇到同样的问题，使用react-native-gesture-handler的点击事件解决了

是的，我也是这样解决的
