### ISSUE TITLE
空白

### ISSUE THREAD

**Issue by Whitehachi** [axerjs/react-native-waterfall-flow#31]
之前是按照FlatList参数来写的，正常显示，但是换了这个，出现编辑器报错
```
<WaterfallFlow //这一行报错
                data={this.state.List}
                refreshing={this.state.reFreshing}
                onRefresh={this.componentDidMount}
                ListFooterComponent={()=>{
                  return(
                  <View>
                    <ActivityIndicator animating={true} color={MD2Colors.red800} />
                  </View>
                  )}}
                renderItem={this.RecommendItem}
                onEndReached={this.MoreRecommend}
                numColumns={2}
                keyExtractor={(item, index)=> index.toString()}
              />
```

**Comment by Whitehachi** [comment]
引入过了的

**Comment by Whitehachi** [comment]
报错内容

没有与此调用匹配的重载。
  第 1 个重载(共 2 个)，“(props: WaterfallFlowProps<any> | Readonly<WaterfallFlowProps<any>>): WaterfallFlow<any>”，出现以下错误。
    类型“{ data: any; refreshing: any; onRefresh: () => void; ListFooterComponent: () => Element; renderItem: ({ item, index, columnIndex }: { item: any; index: any; columnIndex: any; }) => Element; onEndReached: () => void; numColumns: number; keyExtractor: (item: any, index: number) => string; }”缺少类型“Readonly<WaterfallFlowProps<any>>”的以下属性: scrollToEnd, scrollToIndex, scrollToItem, scrollToOffset 及其他 13 项。
  第 2 个重载(共 2 个)，“(props: WaterfallFlowProps<any>, context: any): WaterfallFlow<any>”，出现以下错误。
    类型“{ data: any; refreshing: any; onRefresh: () => void; ListFooterComponent: () => Element; renderItem: ({ item, index, columnIndex }: { item: any; index: any; columnIndex: any; }) => Element; onEndReached: () => void; numColumns: number; keyExtractor: (item: any, index: number) => string; }”缺少类型“Readonly<WaterfallFlowProps<any>>”的以下属性: scrollToEnd, scrollToIndex, scrollToItem, scrollToOffset 及其他 13 项。

**Comment by NERV-qiruoyi** [comment]
我也遇到同样的问题了，请问解决了吗

**Comment by yzw7489757** [comment]
我也遇到相同问题


> 之前是按照FlatList参数来写的，正常显示，但是换了这个，出现编辑器报错
> 
> ```
> <WaterfallFlow //这一行报错
>                 data={this.state.List}
>                 refreshing={this.state.reFreshing}
>                 onRefresh={this.componentDidMount}
>                 ListFooterComponent={()=>{
>                   return(
>                   <View>
>                     <ActivityIndicator animating={true} color={MD2Colors.red800} />
>                   </View>
>                   )}}
>                 renderItem={this.RecommendItem}
>                 onEndReached={this.MoreRecommend}
>                 numColumns={2}
>                 keyExtractor={(item, index)=> index.toString()}
>               />
> ```

**Comment by whytimber** [comment]
add {...({} as any)} to WaterfallFlow props
