### ISSUE TITLE
如何设置item之间的间距

### ISSUE THREAD

**Issue by hnny09** [axerjs/react-native-waterfall-flow#5]

**Comment by axeryu** [comment]
item之间的间距你可以在renderItem中去处理, 暴露出了columnIndex，表示当前item在第几列，这样你就能够自由的控制item的上下左右间距了，例如：
> 注意：padding的部分也要计算在item的高度中
```js
renderItem = {({ item, index, columnIndex }) => {
  return (
    <View
      style={{
        paddingLeft: columnIndex === 0 ? 12 : 6,
        paddingRight: columnIndex === 0 ? 6 : 12,
        paddingTop: 3,
        paddingBottom: 3
      }}
    >
    <View/>
  )
}}
```

**Comment by axeryu** [comment]
@hnny09 上面的回复能够解答你的疑惑吗 ？

**Comment by hnny09** [comment]
我发现另外一个问题：当react-native-waterfall-flow放在scrollView并且未在屏幕上时，滑动到屏幕内时react-native-waterfall-flow不展示

**Comment by axeryu** [comment]
@hnny09 不建议将react-native-waterfall-flow嵌套在scrollView内，可以贴一下你的代码看看吗

- react-native-waterfall-flow就是一个滚动view，你可以像FlatList一样使用它，如果多个滚动嵌套将带来很大的性能问题

- react-native-waterfall-flow支持自定义头部，ListHeaderComponent 我想能满足你的需求，可查看 [样例代码](https://github.com/axerjs/react-native-waterfall-flow/blob/main/examples/App.jsx)

**Comment by hnny09** [comment]
FlatList组件刷新几次后，onLayoutheight会返回为0，你遇到这种情况没？
onLayout={e => {
          const { nativeEvent } = e;
          const { height } = nativeEvent.layout;
          console.log("onLayoutheight:" + height);
   }
}

**Comment by axeryu** [comment]
> FlatList组件刷新几次后，onLayoutheight会返回为0，你遇到这种情况没？ onLayout={e => { const { nativeEvent } = e; const { height } = nativeEvent.layout; console.log("onLayoutheight:" + height); } }

@hnny09 我没有遇到过这样的问题，你可以运行下[示例项目](https://github.com/axerjs/react-native-waterfall-flow/blob/main/examples/App.jsx)，如果还不能解决你的问题，可以将你的代码仓库发给我看看

**Comment by axeryu** [comment]
> FlatList组件刷新几次后，onLayoutheight会返回为0，你遇到这种情况没？ onLayout={e => { const { nativeEvent } = e; const { height } = nativeEvent.layout; console.log("onLayoutheight:" + height); } }

更新到了1.1.0版本，无需再手动设置item的高度了，试试看还会不会出现onLayoutheight返回为0的情况

**Comment by hnny09** [comment]
好的
